# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([ name: 'Star Wars' ,  name: 'Lord of the Rings' ])
#   Character.create(name: 'Luke', movie: movies.first)
Job.destroy_all
Job.create!(
    [{jobNum: '03972', poDate: '', customer: 'Markwest', description: 'Inspect and Repair 12HAH-18T Pump',
     needBom: true, bomDone: true, status: 'Production', progress: 'Ready',
     priority: '1'},
     {jobNum: '03979',poDate: '',customer: 'Markwest', description: '1 - 5Gal Seal Pot and Stand, 316SS',
     needBom: false, bomDone: false, status: 'Production', progress: 'Ready - Keep allocated for customer',
     priority: '2'},
     {jobNum: '04164',poDate: '',customer: 'PT Freeport', description: '1 - 14BCH-2T Pump',
     needBom: false, bomDone: false, status: 'Production', progress: 'Need to send checks for 14BCH Impellers and Bowls',
     priority: '3'},
     {jobNum: '04169',poDate: '',customer: 'Operadora de Minas', description: 'Various Turbine Parts',
     needBom: false, bomDone: false, status: 'Production', progress: 'Ready - Waiting for customer payment',
     priority: '4'},
     {jobNum: '04199',poDate: '',customer: 'PT Freeport', description: 'Packing Box only B/O',
     needBom: false, bomDone: false, status: 'Production', progress: '',
     priority: '5'},
     {jobNum: '04243',poDate: '',customer: 'PT Freeport', description: '1 - Stuffing Assembly 1-1/2in x 5in Regulator',
     needBom: true, bomDone: true, status: 'Production', progress: '',
     priority: '6'},
     {jobNum: '04253',poDate: '',customer: 'PT Freeport', description: '4 - 14BCH Impellers',
     needBom: false, bomDone: false, status: 'Production', progress: '',
     priority: '7'},
     {jobNum: '04258',poDate: '',customer: 'PT Freeport', description: '1 - Stuffing Assembly, 1 - 14BCH Impeller, 1 - Bearing',
     needBom: true, bomDone: true, status: 'Production', progress: '',
     priority: '8'},
     {jobNum: '04279',poDate: '',customer: 'PT Freeport', description: '1 - 1403H-2T Turbine and Various Parts',
     needBom:'', bomDone:'',
     status: 'Production', progress: '', priority: '9'},
     {jobNum: '04286',poDate: '',customer: 'Basin Electric', description: '1 - 8BCAL-2T Turbine Pump',
     needBom:'', bomDone:'',
     status: 'Production', progress: '', priority: '10'},
     {jobNum: '04229',poDate: '',customer: 'RPM - Shawnee', description: '1 - Motor painted Blue',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '11'},
     {jobNum: '04230',poDate: '',customer: 'RPM - Shawnee', description: '1 - 300HP Baldor Horizontal  Motor',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '12'},
     {jobNum: '04231',poDate: '',customer: 'RPM - Shawnee', description: '1 - 150HP WEG Horizontal Motor',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '13'},
     {jobNum: '04244',poDate: '',customer: 'RPM - Lubbock', description: '1 - Test Motor',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '14'},
     {jobNum: '03493',poDate: '',customer: 'Markwest', description: 'Pumps Shipped. Need testing.',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '15'},
     {jobNum: '03653',poDate: '',customer: 'RPM - Shawnee', description: '5 - discharges',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '16'},
     {jobNum: '03983',poDate: '',customer: 'RPM - Shawnee', description: '10 - Intakes, 316SS',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '17'},
     {jobNum: '04085',poDate: '',customer: 'RPM - Shawnee', description: '10 - Re-machine Thrust Chamber Housings',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '18'},
     {jobNum: '04201',poDate: '',customer: 'RPM - Shawnee', description: '19 - P6-360 Impellers and Diffusers',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '19'},
     {jobNum: '04203',poDate: '',customer: 'RPM - Shawnee', description: '110 - PS02916 Spacer Sleeves, B/O',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '20'},
     {jobNum: '04204',poDate: '',customer: 'RPM - Shawnee', description: '48 - PS02645 Shaft Sleeves',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '21'},
     {jobNum: '04208',poDate: '',customer: 'RPM - Shawnee', description: '15 - PS01825A ITLP Heads',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '22'},
     {jobNum: '04213',poDate: '',customer: 'RPM - Shawnee', description: '10 - PS00759 Discharge, 316SS',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '23'},
     {jobNum: '04214',poDate: '',customer: 'RPM - Shawnee', description: '10 - PS01853 ITLP Housing',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '24'},
     {jobNum: '04216',poDate: '',customer: 'RPM - Shawnee', description: '10 - PS01854B ITLP Base',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '25'},
     {jobNum: '04217',poDate: '',customer: 'RPM - Shawnee', description: '10 - PS00184 TLP Flinger',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '26'},
     {jobNum: '04218',poDate: '',customer: 'RPM - Shawnee', description: '10 - PS00243 Seal Plate',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '27'},
     {jobNum: '04267',poDate: '',customer: 'RPM - Shawnee', description: '2 - 8SDCH-19T, 2 - 8SDCH-14T, 2 - 17ft Skids, 2 - 15ft Skids',
     needBom: true, bomDone: true,
     status: 'Production', progress: '', priority: '28'},
     {jobNum: '04272',poDate: '',customer: 'RPM - Shawnee', description: '20 Each - PS03293, PS03275, and PS00392C',
     needBom: false, bomDone: false,
     status: 'Engineering', progress: '', priority: '29'},
     {jobNum: '04287',poDate: '',customer: 'RPM - Shawnee', description: '4 - PS01855C ITLP Shafts',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '30'},
     {jobNum: '04288',poDate: '',customer: 'RPM - Shawnee', description: '1 - Machined Housing',
     needBom: false, bomDone: false,
     status: 'Production', progress: '', priority: '31'}]);
